services:
  server:
    build: .
    container_name: servidor
    environment:
      - MODE=server
      - SERVER_ADDR=:8080
    ports:
      - "8080:8080"
  
  client:
    build: .
    environment:
      - MODE=client
      - SERVER_ADDR=server:8080
    depends_on:
      - server
    stdin_open: true  # mantém o stdin aberto para digitar
    tty: true         # cria um terminal interativo
  
  test:
    build: 
      context: .
      target: tester
    environment:
      - MODE=test
    volumes:
      - .:/app  # monta o código para facilitar desenvolvimento
    command: go test ./test/... -v  # executa todos os testes na pasta test
    profiles:
      - testing  # só executa quando especificado