services:
  server:
    build: .
    container_name: servidor
    environment:
      - MODE=server
      - SERVER_ADDR=:8080
    ports:
      - "8080:8080"

  client:
    build: .
    environment:
      - MODE=client
      - SERVER_ADDR=server:8080
    depends_on:
      - server
    stdin_open: true  # mantém o stdin aberto para digitar
    tty: true         # cria um terminal interativo